"""initial

Revision ID: 18ae595bd7bc
Revises: 
Create Date: 2025-11-09 18:12:36.845633

"""
from typing import Sequence, Union
from passlib.context import CryptContext
from datetime import date, time

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18ae595bd7bc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Хэширование пароля
pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")
def get_password_hash(password: str) -> str:
    return pwd_context.hash(password)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rooms',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role_id', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('memberships',
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('trainings',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trainer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('training_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['training_id'], ['trainings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'training_id', name='uq_user_training')
    )
    # ### Insert Initial Data ###
    roles_table = sa.table(
        'roles',
        sa.column("id", sa.Integer),
        sa.column("name", sa.String),
    )
    op.bulk_insert(
        roles_table,
        [
            {"id": 1, "name": "client"},
            {"id": 2, "name": "trainer"},
            {"id": 3, "name": "admin"},
        ],
    )
    users_table = sa.table(
        'users',
        sa.column("id", sa.Integer),
        sa.column("phone_number", sa.String),
        sa.column("first_name", sa.String),
        sa.column("last_name", sa.String),
        sa.column("email", sa.String),
        sa.column("password", sa.String),
        sa.column("role_id", sa.Integer),
    )
    op.bulk_insert(
        users_table,
        [
            {
                "id": 1,
                "phone_number": "+70000000001",
                "first_name": "Иван",
                "last_name": "Петров",
                "email": "client@example.com",
                "password": get_password_hash("client"),
                "role_id": 1,
            },
            {
                "id": 2,
                "phone_number": "+70000000002",
                "first_name": "Сергей",
                "last_name": "Попов",
                "email": "trainer@example.com",
                "password": get_password_hash("trainer"),
                "role_id": 2,
            },
            {
                "id": 3,
                "phone_number": "+70000000003",
                "first_name": "Админ",
                "last_name": "Системы",
                "email": "admin@example.com",
                "password": get_password_hash("admin"),
                "role_id": 3,
            },
        ],
    )
    rooms_table = sa.table(
        "rooms",
        sa.column("id", sa.Integer),
        sa.column("title", sa.String),
        sa.column("capacity", sa.Integer),
    )
    op.bulk_insert(
        rooms_table,
        [
            {"id": 1, "title": "Зал №1", "capacity": 15},
            {"id": 2, "title": "Зал №2", "capacity": 10},
            {"id": 3, "title": "Тренажерный зал", "capacity": 30},
        ],
    )
    trainings_table = sa.table(
        "trainings",
        sa.column("id", sa.Integer),
        sa.column("title", sa.String),
        sa.column("description", sa.Text),
        sa.column("date", sa.Date),
        sa.column("start_time", sa.Time),
        sa.column("end_time", sa.Time),
        sa.column("trainer_id", sa.Integer),
        sa.column("room_id", sa.Integer),
    )
    op.bulk_insert(
        trainings_table,
        [
            {
                "id": 1,
                "title": "Йога для начинающих",
                "description": "Расслабляющее занятие для всех уровней подготовки.",
                "date": date(2025, 12, 10),
                "start_time": time(9, 0),
                "end_time": time(10, 0),
                "trainer_id": 2,
                "room_id": 1,
            },
            {
                "id": 2,
                "title": "Кардио тренировка",
                "description": "Интенсивное занятие на выносливость и жиросжигание.",
                "date": date(2025, 12, 11),
                "start_time": time(18, 0),
                "end_time": time(19, 0),
                "trainer_id": 2,
                "room_id": 2,
            },
        ],
    )
    subs_table = sa.table(
        "subscriptions",
        sa.column("id", sa.Integer),
        sa.column("title", sa.String),
        sa.column("price", sa.Integer),
        sa.column("duration_days", sa.Integer),
    )
    op.bulk_insert(
        subs_table,
        [
            {"id": 1, "title": "Базовый", "price": 3000, "duration_days": 30},
            {"id": 2, "title": "Стандарт", "price": 5500, "duration_days": 60},
            {"id": 3, "title": "Премиум", "price": 8000, "duration_days": 90},
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    op.drop_table('trainings')
    op.drop_table('memberships')
    op.drop_table('users')
    op.drop_table('subscriptions')
    op.drop_table('rooms')
    op.drop_table('roles')
    # ### end Alembic commands ###
